### ISSUE TITLE
demo.py and human_body_prior

### ISSUE THREAD

**Issue by lphhh123** [jiashunwang/Long-term-Motion-in-3D-Scenes#12]
Thanks for your interesting work. When I use  human_body_prior  committed before August 31, 2020, I encounter an error message with missing parameters.How to solve this situation? Thank you very much.
![微信图片_20240403202225](https://github.com/jiashunwang/Long-term-Motion-in-3D-Scenes/assets/152965459/0bd12729-11fb-445a-a6f9-1b47aeafa38d)

**Comment by jiashunwang** [comment]
Can you try this? https://drive.google.com/file/d/1u7gSbgboam6bgN4yrSQ20n51f1gI9Nz3/view?usp=sharing

**Comment by lphhh123** [comment]
> Can you try this? https://drive.google.com/file/d/1u7gSbgboam6bgN4yrSQ20n51f1gI9Nz3/view?usp=sharing

Thank you very much, this was very helpful to me, but I have encountered another problem, I don’t know where 
 ./data/body_segments  is.
![微信图片_20240407114404](https://github.com/jiashunwang/Long-term-Motion-in-3D-Scenes/assets/152965459/0a9f5807-c8fe-41b1-80a8-81549c7811fc)

**Comment by lphhh123** [comment]
> Can you try this? https://drive.google.com/file/d/1u7gSbgboam6bgN4yrSQ20n51f1gI9Nz3/view?usp=sharing

Thank you very much, this was very helpful to me

**Comment by lphhh123** [comment]
> Can you try this? https://drive.google.com/file/d/1u7gSbgboam6bgN4yrSQ20n51f1gI9Nz3/view?usp=sharing

Thank you very much, this is very helpful to me.
