### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by seonghyunkim1212** [jiashunwang/Long-term-Motion-in-3D-Scenes#2]
Hi, thanks for your nice work!

How can I get a pre-trained model(0811_in_256_4.model and point.model) of pointnet?

Could you share the pre-trained model of pointnet?

Also, could you share the pre-trained model of cvae, RouteNet and PoseNet?

Thanks!

**Comment by jiashunwang** [comment]
Hi
We also provide our pretrained model https://drive.google.com/file/d/1QyUWmvepAXKk_WYd2C-ZB6CEnl4zpjBS/view?usp=sharing
For the pointnet model, you can always use point.model

**Comment by seonghyunkim1212** [comment]
Awesome!

Thanks for your quick reply!

seonghyun
