### ISSUE TITLE
About the middle position (sub goal).

### ISSUE THREAD

**Issue by Silverster98** [jiashunwang/Long-term-Motion-in-3D-Scenes#5]
I have noticed that you set the middle position manually in `demo.ipynb`. So, I am wondering that if I want to synthesize a long-term sequence with the start position and end position as input, I need to manually set the middle position by myself? According to my understanding, the sub-goal network proposed in your paper only synthesizes the body with a given position, it doesn't generate a middle position in a long-term sequence synthesis, am I right? I am looking forward to your reply.

**Comment by jiashunwang** [comment]
Hi
As we described in the paper, sub goal positions are given. The purpose of this is we are not doing prediction but synthesis, we want people to walk to different places and interacting with different things. You can set sub goal near the bed, sofa or whereever you want. Basically, in our setting, the sub goal, start and end positions are the same thing. You can add a new position after the end, and the previous end would become a sub goal. You can keep adding positions to make this motion longer. 

And also, our short-term motion is actually not short, the model can complete a relatively long-distance motion.
So if you just want the person walk from the beginning to the end, you don't need to add sub goal position. Optimization process also works for a single short-term motion. But if you want this person to walk around, interact with different things and so on, you can add some interesting positions as you want.

If you do not want to set it manually, you can randomly sample some positions. (Please pay attention to the height.)
