### ISSUE TITLE
Commit of human_body_prior used for this repo?

### ISSUE THREAD

**Issue by azuki-miho** [jiashunwang/Long-term-Motion-in-3D-Scenes#6]
Thanks for your interesting work. When I attempt to use the code in generate_sub_data.ipynb, it seems human_body_prior has changed its function, can you tell me which commit of human_body_prior do you use for the generate_sub_data.ipynb?

**Comment by jiashunwang** [comment]
Hi!
I think it is the one committed on Aug 31, 2020 or the one before that, since I submitted it to CVPR 2021. I used it before Nov. 2020.

**Comment by lphhh123** [comment]
> Thanks for your interesting work. When I attempt to use the code in generate_sub_data.ipynb, it seems human_body_prior has changed its function, can you tell me which commit of human_body_prior do you use for the generate_sub_data.ipynb?

I encountered the same issue as you. Have you found the right version? I would be very grateful if you could tell me.
